name: Deploy React to Cloudflare Subdomain: staging.rezly.io
on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install dependencies
          run: npm install

        - name: Build project
          run: npm run build

        - name: Sync files to Cloudflare
          uses: cloudflare/pages-action@v1
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: "rezly.io"
            directory: "build"
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}